spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mismancelaleddin@gmail.com
    password: 'kvyllzyavetxflef'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    username: application
    password: '123app*.'
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      maximum-pool-size: 7
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 1792
        useServerPrepStmts: true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          batch_versioned_data: true
logging:
  level:
    com:
      simple: debug
shop:
  mail-receiver: celaleddinmisman@gmail.com
